<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Permission::insert([
            [
                'name' => 'Agent Anasayfa',
                'description' => 'Çağrı Merkezi Temsilcilerinin e-posta gönderimi yaptığı sayfanın erişim yetkisi.',
                'route_name' => 'front.homepage',
                'back_route_name' => NULL,
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agent E-Posta Gönder',
                'description' => 'Çağrı Merkezi Temsilcilerinin e-posta gönderimi yaptığı işlemin erişim yetkisi.',
                'route_name' => 'front.sender',
                'back_route_name' => 'front.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gönderilen E-Postalar Sayfası',
                'description' => 'Çağrı Merkezi Temsilcilerinin gönderdiği e-postaları görüntülediği sayfanın erişim yetkisi.',
                'route_name' => 'front.sent-emails',
                'back_route_name' => 'front.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yönetim Paneli Anasayfa',
                'description' => 'Yönetim Panelinin Anasayfasının erişim yetkisi.',
                'route_name' => 'admin.homepage',
                'back_route_name' => 'front.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bilgisi Eksik Müşteriler Sayfası',
                'description' => 'Profili oluşturulmuş ancak bilgileri eksik olan müşterilerin listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.back-office.customer-with-no-information',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aranacak Müşteriler Sayfası',
                'description' => 'Faturası gönderildikten sonra 1 iş günü süre geçmiş fakat faturaya dair bilgilendirme araması yapılmamış müşterilerin listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.back-office.customers-to-be-called',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arandı İşaretle',
                'description' => 'Faturası gönderildikten sonra 1 iş günü süre geçmiş faturaya ait müşterinin arandı işareti yapılmasına izin veren işlemin erişim yetkisi.',
                'route_name' => 'admin.back-office.checked-called-invoice',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gönderilecek Faturalar Sayfası',
                'description' => 'Muhasebe tarafından yüklenmiş fakat henüz müşterilere gönderilmemiş faturaların listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.back-office.invoices-to-be-sent',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fatura Gönder',
                'description' => 'Muhasebe tarafından yüklenmiş fakat henüz müşterilere gönderilmemiş faturaların gönderilmesine izin veren işlemin erişim yetkisi.',
                'route_name' => 'admin.back-office.send-invoice-email',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uyarı Bekleyen Müşteriler Sayfası',
                'description' => 'Faturasını zamanında ödemeyen müşterilerin listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.back-office.alert-emails',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uyarı E-Postası Gönder',
                'description' => 'Faturasını zamanında ödemeyen müşterilere uyarı e-postası gönderilmesine izin veren işlemin erişim yetkisi.',
                'route_name' => 'admin.back-office.send-alert-email',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhasebe Sayfası',
                'description' => 'Muhasebe işlemlerinin yapıldığı sayfanın erişim yetkisi.',
                'route_name' => 'admin.notifications.accounting',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avukat Sayfası',
                'description' => 'Avukat işlemlerinin yapıldığı sayfanın erişim yetkisi.',
                'route_name' => 'admin.notifications.lawyer',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kullanıcılar Sayfası',
                'description' => 'Kullanıcıların listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.users',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kullanıcı Ekleme Sayfası',
                'description' => 'Yeni kullanıcı eklemek için kullanılan sayfanın erişim yetkisi.',
                'route_name' => 'admin.users.add',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kullanıcı Ekleme İşlemi',
                'description' => 'Yeni kullanıcı eklemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.users.add.post',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kullanıcı Düzenleme Sayfası',
                'description' => 'Kullanıcı bilgilerini düzenlemek için kullanılan sayfanın erişim yetkisi.',
                'route_name' => 'admin.users.edit',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kullanıcı Düzenleme İşlemi',
                'description' => 'Kullanıcı bilgilerini düzenlemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.users.edit-post',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gönderilen E-Postalar Sayfası',
                'description' => 'Sistem tarafından gönderilen e-postaların listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.sent-emails',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gönderilen E-Posta Detay Sayfası',
                'description' => 'Sistem tarafından gönderilen e-postaların detaylarının görüntülendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.view-sent-mail',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gönderilen E-Posta Güncelleme İşlemi',
                'description' => 'Sistem tarafından gönderilen e-postaların detaylarının güncellenmesine izin veren işlemin erişim yetkisi.',
                'route_name' => 'admin.update-sent-mail',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Onay E-Postası Gönderme İşlemi',
                'description' => 'Sistem tarafından gönderilen e-postaların detaylarının güncellenmesine izin veren işlemin erişim yetkisi.',
                'route_name' => 'admin.send-approval-email',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raporlar Sayfası',
                'description' => 'Sistemdeki raporların listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.report',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rapor Görüntüleme İşlemi',
                'description' => 'Seçilen agentin raporunu görüntülemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.report.post',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Panel Logları Sayfası',
                'description' => 'Sistemdeki panel loglarının listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.logs.admin',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agent Logları Sayfası',
                'description' => 'Sistemdeki agent loglarının listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.logs.front',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Log Detay Sayfası',
                'description' => 'Sistemdeki logların detaylarının görüntülendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.logs.view',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Müşteriler Sayfası',
                'description' => 'Sistemdeki müşterilerin listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.customers',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Müşteri Detay Sayfası',
                'description' => 'Sistemdeki müşterilerin detaylarının görüntülendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.customer.detail',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeni Sipariş Oluşturma',
                'description' => 'Müşteri detay sayfasında yeni sipariş oluşturmak için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.customer.add-new-order',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yorumu Reddetme İşlemi',
                'description' => 'Müşterinin siparişine ait yorum silinemedi olarak işaretlemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.customer.reject-comment',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fatura Yükleme İşlemi',
                'description' => 'Müşterinin siparişine ait faturayı yüklemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.customer.upload-invoice',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fatura Ödendi İşlemi',
                'description' => 'Müşterinin siparişine ait faturayı ödendi olarak işaretlemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.customer.update-invoice-payment',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Müşteri Güncelleme İşlemi',
                'description' => 'Müşterinin bilgilerini güncellemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.customer.update-customer-detail',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yorum İşleme Alındı İşlemi',
                'description' => 'Avukatın müşterinin siparişine ait yorumu işleme aldığını işaretlemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.customer.take-a-lawyer',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'İşlemdeki Siparişler Sayfası',
                'description' => 'Sistemdeki işlemde olan siparişlerin listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.orders.in-processing',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tamamlanan Siparişler Sayfası',
                'description' => 'Sistemdeki tamamlanan siparişlerin listelendiği sayfanın erişim yetkisi.',
                'route_name' => 'admin.orders.completed',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yetkiler Sayfası',
                'description' => 'Sistemde kayıtlı yetkilerin ayarlandığı sayfanın erişim yetkisi.',
                'route_name' => 'admin.permissions',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeni Yetki Oluşturma',
                'description' => 'Sistemde yeni bir yetki oluşturmak için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.permissions.new',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yetki Güncelleme',
                'description' => 'Sistemde kayıtlı bir yetkinin bilgilerini güncellemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.permissions.edit',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yetki Silme',
                'description' => 'Sistemde kayıtlı bir yetkinin silinmesi için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.permissions.delete',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yetki Grupları Sayfası',
                'description' => 'Sistemde kayıtlı yetki gruplarının ayarlandığı sayfanın erişim yetkisi.',
                'route_name' => 'admin.permission-groups',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeni Yetki Grubu Oluşturma',
                'description' => 'Sistemde yeni bir yetki grubu oluşturmak için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.permission-groups.new',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yetki Grubu Güncelleme',
                'description' => 'Sistemde kayıtlı bir yetki grubunun bilgilerini güncellemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.permission-groups.edit',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yetki Grubu Silme',
                'description' => 'Sistemde kayıtlı bir yetki grubunun silinmesi için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.permission-groups.delete',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roller Sayfası',
                'description' => 'Sistemde kayıtlı rollerin ayarlandığı sayfanın erişim yetkisi.',
                'route_name' => 'admin.roles',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeni Rol Oluşturma',
                'description' => 'Sistemde yeni bir rol oluşturmak için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.roles.new',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rol Güncelleme',
                'description' => 'Sistemde kayıtlı bir rolün bilgilerini güncellemek için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.roles.edit',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rol Silme',
                'description' => 'Sistemde kayıtlı bir rolün silinmesi için kullanılan işlemin erişim yetkisi.',
                'route_name' => 'admin.roles.delete',
                'back_route_name' => 'admin.homepage',
                'is_editable' => true,
                'is_erasable' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


    }
}
